create extension if not exists "pgcrypto";
create table if not exists public.posts (id uuid primary key default gen_random_uuid(),slug text unique not null,title text not null,domain text not null check (domain in ('decode','execute','deploy','trek','roots')),excerpt text default '',body text default '',thesis text default '',tools text default '',status text not null default 'draft' check (status in ('draft','published')),published_at date default current_date,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.posts enable row level security;
create table if not exists public.site_content (key text primary key,value jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now());
alter table public.site_content enable row level security;
create policy "site content is public" on public.site_content for select using (true);
create policy "authenticated author inserts site content" on public.site_content for insert to authenticated with check (true);
create policy "authenticated author updates site content" on public.site_content for update to authenticated using (true) with check (true);
insert into public.site_content(key,value) values ('home','{"hero_title":"我不展示答案。","hero_emphasis":"我记录理解发生的过程。","hero_deck":"一个实用主义者的公开工作台：在语言、商业、技术、身体与来处之间，寻找那些尚未被命名的连接。","manifesto":"保持好奇，但不把好奇误认为深刻；相信工具，但不把工具误认为能力；持续行动，同时给缓慢留下位置。"}'::jsonb) on conflict(key) do nothing;
create policy "published posts are public" on public.posts for select using (status = 'published' or auth.role() = 'authenticated');
create policy "authenticated author can insert" on public.posts for insert to authenticated with check (true);
create policy "authenticated author can update" on public.posts for update to authenticated using (true) with check (true);
create policy "authenticated author can delete" on public.posts for delete to authenticated using (true);
insert into public.posts (slug,title,domain,excerpt,thesis,tools,status,published_at) values ('formidable','从 formidable 的词根，看“恐惧”如何变成“强大”','decode','一个词的含义从来不是定义，而是一段被压缩过的社会经验。','语言像化石，保存着人类曾经害怕什么。','词源词典 × 3 / Gemini 辅助对照 / 42 min','published','2026-07-08'),('cola-cost','一罐可乐的成本，不在铝罐里','execute','把一个熟悉的消费品拆回供应链，重新理解品牌、渠道与规模。','利润不是售价减成本，而是系统里每个选择的残影。','公开财报 / 零售访谈 / 手工计算','published','2026-07-05'),('two-ai','我怎样让两个 AI 为同一个网站争论','deploy','一个负责主导，一个负责反驳；人的价值不在发言最多，而在最终取舍。','真正好用的 AI 工作流，最后看起来不像 AI。','Codex + Gemini / 17 次迭代 / 本地验证','published','2026-06-29') on conflict (slug) do nothing;
create table if not exists public.comments (id uuid primary key default gen_random_uuid(),kind text not null default 'comment' check (kind in ('comment','message')),post_slug text,name text not null check (char_length(name) between 1 and 60),email text not null check (char_length(email) between 3 and 160),body text not null check (char_length(body) between 2 and 2000),status text not null default 'pending' check (status in ('pending','approved','rejected')),created_at timestamptz not null default now(),reviewed_at timestamptz);
alter table public.comments enable row level security;
drop policy if exists "approved comments are public" on public.comments;
drop policy if exists "visitors can submit comments" on public.comments;
drop policy if exists "authenticated author can review comments" on public.comments;
drop policy if exists "authenticated author can delete comments" on public.comments;
create policy "approved comments are public" on public.comments for select using (status = 'approved' or auth.role() = 'authenticated');
create policy "visitors can submit comments" on public.comments for insert to anon,authenticated with check (status = 'pending');
create policy "authenticated author can review comments" on public.comments for update to authenticated using (true) with check (true);
create policy "authenticated author can delete comments" on public.comments for delete to authenticated using (true);
create index if not exists comments_post_slug_status_idx on public.comments(post_slug,status,created_at desc);
alter table public.posts add column if not exists firebase_id text unique;
alter table public.posts add column if not exists tags text[] not null default '{}';
alter table public.comments add column if not exists firebase_id text unique;
create table if not exists public.books (id uuid primary key default gen_random_uuid(),firebase_id text unique,title text not null,author text default '',cover_url text default '',status text not null default 'Reading' check (status in ('Reading','Read','To Read')),rating integer not null default 0 check (rating between 0 and 5),review text default '',language text not null default 'Chinese' check (language in ('Chinese','English')),custom_lists text[] not null default '{}',linked_post_slug text,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.books enable row level security;
drop policy if exists "books are public" on public.books;
drop policy if exists "authenticated author inserts books" on public.books;
drop policy if exists "authenticated author updates books" on public.books;
drop policy if exists "authenticated author deletes books" on public.books;
create policy "books are public" on public.books for select using (true);
create policy "authenticated author inserts books" on public.books for insert to authenticated with check (true);
create policy "authenticated author updates books" on public.books for update to authenticated using (true) with check (true);
create policy "authenticated author deletes books" on public.books for delete to authenticated using (true);
create index if not exists books_sort_order_idx on public.books(sort_order,created_at desc);
create table if not exists public.subscribers (id uuid primary key default gen_random_uuid(),firebase_id text unique,email text not null unique,created_at timestamptz not null default now(),source text default 'firebase');
alter table public.subscribers enable row level security;
drop policy if exists "visitors can subscribe" on public.subscribers;
drop policy if exists "authenticated author reads subscribers" on public.subscribers;
create policy "visitors can subscribe" on public.subscribers for insert to anon,authenticated with check (true);
create policy "authenticated author reads subscribers" on public.subscribers for select to authenticated using (true);
alter table public.posts add column if not exists notification_sent_at timestamptz;
