import Link from 'next/link'
import Logo from '../components/logo'
import {createClient,isConfigured} from '@/lib/supabase/server'
import './search.css'
export const dynamic='force-dynamic'
export const metadata={title:'搜索',description:'检索日志、书单与阅读轨迹。'}
const text=v=>String(v||'').toLocaleLowerCase('zh-CN')
export default async function SearchPage({searchParams}){const q=String((await searchParams)?.q||'').trim().slice(0,80),needle=text(q);let posts=[],books=[],trails=[];if(q&&isConfigured()){const db=await createClient();const [{data:p},{data:b},{data:t}]=await Promise.all([db.from('posts').select('id,slug,title,excerpt,domain,tags,published_at').eq('status','published').order('published_at',{ascending:false}),db.from('books').select('id,title,author,review,custom_lists,linked_post_slug').order('sort_order'),db.from('trails').select('id,slug,title,summary,status').eq('status','published').order('updated_at',{ascending:false})]);posts=(p||[]).filter(x=>text([x.title,x.excerpt,x.domain,...(x.tags||[])].join(' ')).includes(needle));books=(b||[]).filter(x=>text([x.title,x.author,x.review,...(x.custom_lists||[])].join(' ')).includes(needle));trails=(t||[]).filter(x=>text([x.title,x.summary].join(' ')).includes(needle))}const count=posts.length+books.length+trails.length;return <main className="search-page"><nav><Link href="/"><Logo compact/></Link><span>GLOBAL INDEX / 全站检索</span><Link href="/logs">日志 ↗</Link></nav><header><small>SEARCH ACROSS CONNECTIONS</small><h1>寻找一条<br/><em>已经出现过的线。</em></h1><form><label htmlFor="q">关键词</label><input id="q" name="q" defaultValue={q} autoFocus placeholder="输入书名、主题、作者或概念"/><button>检索 →</button></form>{q&&<p>{String(count).padStart(3,'0')} RESULTS / “{q}”</p>}</header>{q&&<section className="search-results"><Result title="日志" items={posts} render={x=><Link href={`/logs/${encodeURIComponent(x.slug)}`}><small>{x.domain} · {x.published_at}</small><h2>{x.title}</h2><p>{x.excerpt}</p></Link>}/><Result title="书单" items={books} render={x=><Link href={`/books#book-${x.id}`}><small>{x.author||'UNKNOWN AUTHOR'}</small><h2>{x.title}</h2><p>{x.review}</p></Link>}/><Result title="轨迹" items={trails} render={x=><Link href={`/trails/${encodeURIComponent(x.slug)}`}><small>TRAIL / CONNECTION</small><h2>{x.title}</h2><p>{x.summary}</p></Link>}/>{!count&&<div className="search-empty">没有找到直接匹配。换一个更短的词，或返回索引继续浏览。</div>}</section>}</main>}
function Result({title,items,render}){if(!items.length)return null;return <section className="result-group"><header><h2>{title}</h2><span>{String(items.length).padStart(2,'0')}</span></header><div>{items.map(x=><article key={x.id}>{render(x)}</article>)}</div></section>}
