'use client'
import {useState} from 'react';import Link from 'next/link';import {createClient} from '@/lib/supabase/client';import {labels} from '@/lib/demo'
const blank={title:'',slug:'',domain:'decode',excerpt:'',body:'',thesis:'',tools:'',status:'draft',published_at:new Date().toISOString().slice(0,10)}
export default function Studio({configured,initialUser,initialPosts}){const [user,setUser]=useState(initialUser),[posts,setPosts]=useState(initialPosts),[edit,setEdit]=useState(blank),[notice,setNotice]=useState('');
 async function login(e){e.preventDefault();const form=new FormData(e.currentTarget),db=createClient();const {data,error}=await db.auth.signInWithPassword({email:form.get('email'),password:form.get('password')});setNotice(error?.message||'登录成功');if(data.user)location.reload()}
 async function recover(e){const form=e.currentTarget.closest('form'),email=new FormData(form).get('email');if(!email)return setNotice('请先填写邮箱。');const db=createClient();const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:`${location.origin}/reset-password`});setNotice(error?.message||'密码设置邮件已发送，请检查收件箱。')}
 async function save(e){e.preventDefault();if(!configured)return setNotice('演示模式：连接 Supabase 后即可保存。');setNotice('正在保存…');const response=await fetch('/api/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(edit)});const data=await response.json();if(!response.ok)return setNotice(data.error||'保存失败');if(data.notification?.error)return setNotice(`文章已保存，但推送失败：${data.notification.error}`);const result=data.notification?.results?.[0];setNotice(result?`已保存并推送：成功 ${result.sent}，失败 ${result.failed}`:'已保存');setTimeout(()=>location.reload(),900)}
 async function remove(id){if(!confirm('确定删除？'))return;const db=createClient();await db.from('posts').delete().eq('id',id);location.reload()}
 if(configured&&!user)return <main className="studio login"><p className="studio-mark">C/ STUDIO</p><h1>进入编辑系统</h1><form onSubmit={login}><label>邮箱<input name="email" type="email" required/></label><label>密码<input name="password" type="password" required/></label><button>登录</button><button className="text-button" type="button" onClick={recover}>首次登录或忘记密码</button><p className="auth-notice" aria-live="polite">{notice}</p></form></main>
 return <main className="studio"><header><div><p>C/ STUDIO · {configured?'CLOUD':'DEMO MODE'}</p><h1>编辑系统</h1></div><div><Link href="/studio/comments">互动审核</Link>　<Link href="/studio/site">网站内容</Link>　<Link href="/">查看网站 ↗</Link></div></header>{!configured&&<div className="setup">尚未连接 Supabase。界面可预览，完成云端配置后即可保存和发布。</div>}<div className="studio-grid"><aside><button onClick={()=>setEdit(blank)}>＋ 新建记录</button>{posts.map(p=><article key={p.id} onClick={()=>setEdit(p)}><small>{labels[p.domain]}</small><h3>{p.title}</h3><span>{p.status||'published'}</span></article>)}</aside><form className="editor" onSubmit={save}><div className="editor-top"><span>{edit.id?'EDIT ENTRY':'NEW ENTRY'}</span>{edit.id&&configured&&<button type="button" onClick={()=>remove(edit.id)}>删除</button>}</div><label>标题<input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})} required/></label><div className="two"><label>链接<input value={edit.slug} onChange={e=>setEdit({...edit,slug:e.target.value})} required/></label><label>栏目<select value={edit.domain} onChange={e=>setEdit({...edit,domain:e.target.value})}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></div><label>摘要<textarea rows="3" value={edit.excerpt||''} onChange={e=>setEdit({...edit,excerpt:e.target.value})}/></label><label>正文（Markdown）<textarea className="body" rows="12" value={edit.body||''} onChange={e=>setEdit({...edit,body:e.target.value})}/></label><label>核心判断<input value={edit.thesis||''} onChange={e=>setEdit({...edit,thesis:e.target.value})}/></label><label>输入与工具<input value={edit.tools||''} onChange={e=>setEdit({...edit,tools:e.target.value})}/></label><div className="two"><label>状态<select value={edit.status||'published'} onChange={e=>setEdit({...edit,status:e.target.value})}><option value="draft">草稿</option><option value="published">发布</option></select></label><label>发布日期<input type="date" value={edit.published_at?.slice(0,10)||''} onChange={e=>setEdit({...edit,published_at:e.target.value})}/></label></div><button className="save">保存记录</button><p>{notice}</p></form></div></main>}
