'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {labels} from '@/lib/demo'
import InteractionForm from './components/interaction-form'
import SubscribeForm from './components/subscribe-form'
import Logo from './components/logo'
export default function HomeClient({posts,content={},aboutText,showStudio=false}){
 const [filter,setFilter]=useState('all'),[selected,setSelected]=useState(null),[menu,setMenu]=useState(false),[aboutOpen,setAboutOpen]=useState(false);const shown=(filter==='all'?posts:posts.filter(p=>p.domain===filter)).slice(0,6)
 useEffect(()=>{document.body.style.overflow=selected||aboutOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[selected,aboutOpen])
 useEffect(()=>{if(!aboutOpen)return;const close=e=>{if(e.key==='Escape')setAboutOpen(false)};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[aboutOpen])
 useEffect(()=>{const open=e=>{const row=e.target.closest('.entry');if(!row||e.target.closest('button'))return;const title=row.querySelector('h3')?.textContent,post=posts.find(p=>p.title===title);if(post)location.href=`/logs/${encodeURIComponent(post.slug)}`};document.addEventListener('click',open);return()=>document.removeEventListener('click',open)},[posts])
 const legacyHero=!content.hero_title||content.hero_title==='我不展示答案。';const heroTitle=legacyHero?'面对复杂。':content.hero_title;const heroEmphasis=legacyHero||content.hero_emphasis==='我记录理解发生的过程。'?'保持欢喜。':content.hero_emphasis;const legacyDeck=!content.hero_deck||content.hero_deck.startsWith('一个实用主义者的公开工作台')||content.hero_deck.startsWith('现实的世界千疮百孔');const heroDeck=legacyDeck?'The theme of my life is complexity-through-joy.':content.hero_deck
 return <><header className={'site-header '+(menu?'nav-open':'')}><a className="wordmark" href="#top" aria-label="CHRIS / FIELD NOTES 首页"><Logo/></a><button className="menu-button" onClick={()=>setMenu(!menu)}>菜单</button><nav><a href="#log">日志</a><Link href="/books">书单</Link><Link href="/trails">轨迹</Link><Link href="/search">搜索</Link><button type="button" className="nav-about" onClick={()=>{setAboutOpen(true);setMenu(false)}}>ABOUT</button><a href="#subscribe">订阅</a>{showStudio&&<Link className="admin-entry" href="/studio">STUDIO ↗</Link>}</nav></header>
 <main id="top"><section className="hero quote-hero"><blockquote className="hero-slogan"><span className="quote-mark" aria-hidden="true">“</span><h1><span>{heroTitle}</span><em>{heroEmphasis}</em></h1><div className="hero-quote-meta"><p className="hero-deck" lang="en">{heroDeck}</p><div className="hero-attribution"><span aria-hidden="true"/><cite>E. B. White</cite></div></div></blockquote></section>
 <section id="log" className="section"><Title>最新日志</Title><div className="filters">{['all','decode','execute','deploy','trek','roots'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x==='all'?'全部':labels[x].split('/ ')[1]}</button>)}<Link className="all-logs-link" href={filter==='all'?'/logs':`/logs?domain=${filter}`}>查看全部 →</Link></div><div>{shown.map((p,i)=><article className="entry" key={p.id}><span>{String(i+1).padStart(2,'0')}</span><div><small>{labels[p.domain].split('/ ')[1]}</small><h3>{p.title}</h3><p>{p.excerpt}</p></div><time>{p.published_at?.slice(5).replace('-','.')}</time>{(p.thesis||p.tools)&&<button onClick={()=>setSelected(p)}>详情</button>}</article>)}</div></section>
 <section id="domains" className="section"><Title>日志分类</Title><div className="domain-grid">{[['decode','解码'],['execute','执行'],['deploy','部署'],['trek','跋涉'],['roots','溯源']].map(x=><Link className="domain-card" key={x[0]} href={`/logs?domain=${x[0]}`}><h3>{x[1]}</h3><span>{posts.filter(p=>p.domain===x[0]).length} 篇</span></Link>)}</div></section>
 <section id="subscribe" className="section subscribe-section"><Title>订阅更新</Title><div className="subscribe-grid"><SubscribeForm/></div></section>
 <section id="message" className="section message-section"><Title>留言</Title><div className="message-grid"><InteractionForm kind="message"/></div></section></main>
 <footer className="site-footer"><span>CHRIS / FIELD NOTES © 2026</span><div className="footer-meta"><button type="button" onClick={()=>setAboutOpen(true)}>ABOUT</button><Link href="/privacy">隐私政策</Link><a href="#top">返回顶部 ↑</a></div></footer>
 {aboutOpen&&<><button className="about-backdrop" onClick={()=>setAboutOpen(false)} aria-label="关闭 ABOUT"/><section className="about-modal" role="dialog" aria-modal="true" aria-label="ABOUT"><header><button type="button" autoFocus onClick={()=>setAboutOpen(false)}>关闭 ×</button></header><p>{aboutText}</p></section></>}
 {selected&&<><button className="backdrop" onClick={()=>setSelected(null)} aria-label="关闭"/><aside className="drawer"><button onClick={()=>setSelected(null)}>关闭 ×</button><h2>日志详情</h2><dl><dt>发布日期</dt><dd>{selected.published_at}</dd>{selected.thesis&&<><dt>核心判断</dt><dd>{selected.thesis}</dd></>}{selected.tools&&<><dt>输入与工具</dt><dd>{selected.tools}</dd></>}</dl></aside></>}</>}
function Title({children}){return <div className="title"><h2>{children}</h2></div>}
