'use client'
import {useEffect,useState} from 'react'
import Link from 'next/link'
import {labels} from '@/lib/demo'
import InteractionForm from './components/interaction-form'
import SubscribeForm from './components/subscribe-form'
import Logo from './components/logo'
export default function HomeClient({posts,content={}}){
 const [filter,setFilter]=useState('all'),[selected,setSelected]=useState(null),[menu,setMenu]=useState(false);const shown=(filter==='all'?posts:posts.filter(p=>p.domain===filter)).slice(0,6)
 useEffect(()=>{document.body.style.overflow=selected?'hidden':'';return()=>{document.body.style.overflow=''}},[selected])
 useEffect(()=>{const open=e=>{const row=e.target.closest('.entry');if(!row||e.target.closest('button'))return;const title=row.querySelector('h3')?.textContent,post=posts.find(p=>p.title===title);if(post)location.href=`/logs/${encodeURIComponent(post.slug)}`};document.addEventListener('click',open);return()=>document.removeEventListener('click',open)},[posts])
 useEffect(()=>{const set=(selector,value)=>{const el=document.querySelector(selector);if(el&&value)el.textContent=value};const h=document.querySelector('.hero h1');if(h&&(content.hero_title||content.hero_emphasis)){h.textContent='';h.append(document.createTextNode(content.hero_title||''),document.createElement('br'));const em=document.createElement('em');em.textContent=content.hero_emphasis||'';h.append(em)}set('.hero-deck',content.hero_deck);set('.connections h2',content.connection_title);set('.connections p',content.connection_body);set('.manifesto blockquote',content.manifesto)},[content])
 return <><header className={'site-header '+(menu?'nav-open':'')}><a className="wordmark" href="#top" aria-label="CHRIS / FIELD NOTES 首页"><Logo/></a><div className="header-status"><i/> SYSTEM ONLINE · PUBLIC INDEX</div><button className="menu-button" onClick={()=>setMenu(!menu)}>INDEX</button><nav><a href="#log">日志</a><Link href="/books">书单</Link><Link href="/trails">轨迹</Link><Link href="/search">搜索</Link><a href="#about">系统说明</a><a href="#subscribe">订阅</a><Link href="/studio">STUDIO ↗</Link></nav></header>
 <main id="top"><section className="hero"><div className="kicker">PERSONAL OPERATING SYSTEM / 个人操作系统</div><h1>我不展示答案。<br/><em>我记录理解发生的过程。</em></h1><p className="hero-deck">一个实用主义者的公开工作台：在语言、商业、技术、身体与来处之间，寻找那些尚未被命名的连接。</p><a className="scroll-cue" href="#status">向下读取 ↓</a></section>
 <section id="status" className="status"><header><span>CURRENT BANDWIDTH</span><span>最近发布 / LIVE INDEX</span></header><div className="status-grid">{posts.slice(0,3).map((p,i)=><Link className="bandwidth-card" key={p.id} href={`/logs/${encodeURIComponent(p.slug)}`}><small>{['LATEST ENTRY','RECENT SIGNAL','IN THE FIELD'][i]}</small><strong>{p.title}</strong><span>{labels[p.domain]||p.domain}</span></Link>)}<article className="metric"><small>ENTRIES INDEXED</small><strong>{String(posts.length).padStart(3,'0')}</strong><span>AND COUNTING</span></article></div></section>
 <section id="log" className="section"><Title no="01" cn="最新刻录" en="RECENT LOGS"/><div className="filters">{['all','decode','execute','deploy','trek','roots'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x==='all'?'全部':labels[x].split('/ ')[1]}</button>)}<Link className="all-logs-link" href={filter==='all'?'/logs':`/logs?domain=${filter}`}>查看全部日志 →</Link></div><div>{shown.map((p,i)=><article className="entry" key={p.id}><span>{String(i+1).padStart(3,'0')}</span><div><small>{labels[p.domain]}</small><h3>{p.title}</h3><p>{p.excerpt}</p></div><time>{p.published_at?.slice(5).replace('-','.')}</time><button onClick={()=>setSelected(p)} aria-label="查看生产现场">[i]</button></article>)}</div></section>
 <section id="domains" className="section"><Title no="02" cn="五种动作" en="按分类阅读 / BROWSE"/><div className="domain-grid">{[['decode','Decode','阅读、语言、历史与观念。','READ / TRACE / EXPLAIN'],['execute','Execute','现实问题、商业判断与执行。','DECIDE / TEST / REVIEW'],['deploy','Deploy','AI、代码与自动化。','BUILD / PROMPT / SHIP'],['trek','Trek','身体、行走与真实世界。','WALK / OBSERVE / ENDURE'],['roots','Roots','来处、记忆与日常习俗。','REMEMBER / LOCATE / KEEP']].map((x,i)=><Link className="domain-card" key={x[0]} href={`/logs?domain=${x[0]}`}><b>0{i+1}</b><h3>{x[1]}</h3><p>{x[2]}</p><span>{x[3]} · {posts.filter(p=>p.domain===x[0]).length} 篇</span></Link>)}</div></section>
 <section className="connections"><div className="map">×<i>●</i><b>○</b></div><div><small>UNEXPECTED CONNECTION / 07</small><h2>“进化”与“商业”都不是向上生长，<br/>而是对环境的暂时适应。</h2><p>网站真正保存的不是分类，而是不同问题之间突然亮起的那条线。</p></div></section>
 <section id="about" className="section manifesto"><Title no="03" cn="系统说明" en="MANIFESTO"/><blockquote>“保持好奇，但不把好奇误认为深刻；相信工具，但不把工具误认为能力；持续行动，同时给缓慢留下位置。”</blockquote></section>
 <section id="subscribe" className="section subscribe-section"><Title no="04" cn="订阅更新" en="SUBSCRIBE"/><div className="subscribe-grid"><p>不追逐更新频率，只在新的日志完成时，发送一封简短通知。</p><SubscribeForm/></div></section>
 <section id="message" className="section message-section"><Title no="05" cn="留下信号" en="LEAVE A NOTE"/><div className="message-grid"><div><p className="message-lead">这里接受问题、线索与不同意见。邮箱仅用于必要回复，不会公开展示。</p><small>所有留言在审核后进入档案。</small></div><InteractionForm kind="message"/></div></section></main>
 <footer><div className="terminal">$ tail -f system.log<br/><span>indexed {posts.length} field notes</span><br/><span>curiosity daemon is running_</span></div><div>CHRIS / FIELD NOTES © 2026 <a href="#top">TOP ↑</a></div></footer>
 {selected&&<><button className="backdrop" onClick={()=>setSelected(null)} aria-label="关闭"/><aside className="drawer"><button onClick={()=>setSelected(null)}>CLOSE ×</button><small>PRODUCTION CONTEXT</small><h2>生产现场</h2><dl><dt>刻录时间</dt><dd>{selected.published_at}</dd><dt>核心判断</dt><dd>{selected.thesis}</dd><dt>输入与工具</dt><dd>{selected.tools}</dd></dl></aside></>}</>}
function Title({no,cn,en}){return <div className="title"><span>{no}</span><h2>{cn}</h2><p>{en}</p></div>}
