'use client'
import {useMemo,useState} from 'react'
import Link from 'next/link'
import {createClient} from '@/lib/supabase/client'

const isActive=row=>row.status==='active'&&Boolean(row.verified_at)
const statusLabel={sent:'已发送',partial:'部分失败',failed:'发送失败',sending:'发送中'}

export default function SubscriberManager({initial,history}){
  const [rows,setRows]=useState(initial),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const shown=useMemo(()=>rows.filter(x=>x.email.toLowerCase().includes(query.toLowerCase())),[rows,query])
  // 只允许停用；读者退订后只能由本人在网站重新订阅，后台不能替他恢复。
  async function deactivate(row){if(!confirm(`确定停止向 ${row.email} 发送邮件？停用后只能由对方在网站重新订阅。`))return;const {error}=await createClient().from('subscribers').update({status:'unsubscribed',updated_at:new Date().toISOString()}).eq('id',row.id);if(error)return setNotice(error.message);setRows(v=>v.map(x=>x.id===row.id?{...x,status:'unsubscribed'}:x))}
  async function send(e){e.preventDefault();if(!confirm('确认向全部有效订阅用户发送这封邮件？此操作不能撤回。'))return;setBusy(true);setNotice('正在发送…');const form=new FormData(e.currentTarget);const response=await fetch('/api/campaigns',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({subject:form.get('subject'),body:form.get('body')})});const data=await response.json();setBusy(false);setNotice(response.ok?`发送完成：成功 ${data.sent}，失败 ${data.failed}`:(data.error||'发送失败'));if(response.ok){e.currentTarget.reset();setTimeout(()=>window.location.reload(),600)}}
  return <main className="studio subscribers-admin"><header><div><h1>订阅用户</h1></div><div><Link href="/studio">日志编辑</Link>　<Link href="/">查看网站 ↗</Link></div></header><section className="audience-stats"><div><strong>{rows.filter(isActive).length}</strong><span>有效订阅</span></div><div><strong>{rows.length}</strong><span>全部用户</span></div><div><strong>{history.length}</strong><span>最近推送</span></div></section><div className="subscriber-layout"><section><div className="list-toolbar"><h2>用户列表</h2><input placeholder="搜索邮箱" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="subscriber-list">{shown.map(row=><article key={row.id}><div><strong>{row.email}</strong><small>{row.source||'website'} · {new Date(row.created_at).toLocaleDateString('zh-CN')}</small></div>{row.status==='unsubscribed'?<span className="subscriber-state">已退订</span>:<button onClick={()=>deactivate(row)} title="停用该订阅">{isActive(row)?'有效':'待生效'} · 停用</button>}</article>)}</div></section><section className="campaign-panel"><h2>手动推送</h2><form onSubmit={send}><label>邮件主题<input name="subject" required maxLength="120"/></label><label>正文<textarea name="body" rows="12" required/></label><button className="save" disabled={busy}>{busy?'发送中…':'预览并群发'}</button></form><p className="campaign-notice">{notice}</p><h3>最近推送</h3>{history.length?history.map(item=><div className="campaign-row" key={item.id}><strong>{item.title}</strong><small>{item.type==='automatic'?'新日志自动推送':'手动群发'} · {statusLabel[item.status]||item.status} · {item.type==='automatic'?`成功 ${item.sent}/${item.total}`:`${item.total} 人`} · {new Date(item.created_at).toLocaleString('zh-CN')}</small></div>):<p>尚无推送记录</p>}</section></div></main>
}
