import {createClient as createAdminClient} from '@supabase/supabase-js'
import {createClient as createSessionClient} from '@/lib/supabase/server'
export const dynamic='force-dynamic'
function esc(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function bodyHtml(body=''){return String(body).replace(/\r\n?/g,'\n').trim().split(/\n\s*\n+/).filter(Boolean).map(block=>{const image=block.match(/!\[[^\]]*\]\((https?:\/\/[^)\s]+)\)|![^\s]*?(https?:\/\/[^\s]+)|(https?:\/\/[^\s]+\.(?:jpg|jpeg|png|gif|webp|avif)(?:\?[^\s]*)?)/i);if(image){const src=image[1]||image[2]||image[3];return `<img src="${esc(src)}" alt="文章配图" style="display:block;width:100%;height:auto;margin:32px 0;border:1px solid #d1d0ca">`}return `<p style="margin:0 0 22px;font:17px/1.9 Georgia,'Noto Serif SC',serif;color:#151713">${esc(block).replace(/\n/g,'<br>')}</p>`}).join('')}
function emailHtml(post){const url=`https://www.chrisreading.ink/logs/${encodeURIComponent(post.slug)}`;return `<!doctype html><html><body style="margin:0;background:#efeee8;color:#151713"><div style="max-width:720px;margin:auto;padding:42px 24px"><div style="border-bottom:1px solid #151713;padding-bottom:14px;font:11px monospace;letter-spacing:.12em">C/ FIELD NOTES <span style="float:right;color:#526b3f">NEW ENTRY</span></div><div style="padding:54px 0 34px"><div style="font:10px monospace;color:#526b3f;letter-spacing:.12em">${esc(post.domain).toUpperCase()} / 最新日志</div><h1 style="margin:18px 0 24px;font:700 44px/1.15 Georgia,'Noto Serif SC',serif;letter-spacing:-.04em">${esc(post.title)}</h1><p style="font:18px/1.7 Georgia,'Noto Serif SC',serif;color:#696d65">${esc(post.excerpt||'')}</p></div><div style="border-top:1px solid #b9b9b2;padding-top:34px">${bodyHtml(post.body||post.excerpt)}</div><a href="${url}" style="display:inline-block;margin-top:28px;padding:13px 18px;background:#151713;color:#efeee8;text-decoration:none;font:11px monospace">在网站阅读与评论 →</a><div style="margin-top:60px;border-top:1px solid #151713;padding-top:14px;font:10px/1.7 monospace;color:#696d65">你收到此邮件，是因为订阅了 CHRIS / FIELD NOTES。<br>本邮件不会发送网站启用订阅前的历史文章。</div></div></body></html>`}
async function deliver(){const db=createAdminClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});const [{data:posts,error:postError},{data:subscribers,error:subscriberError}]=await Promise.all([db.from('posts').select('id,slug,title,excerpt,body,domain').eq('status','published').is('notification_sent_at',null).order('published_at',{ascending:true}),db.from('subscribers').select('email').order('created_at')]);if(postError||subscriberError)return Response.json({error:postError?.message||subscriberError?.message},{status:500});const results=[];for(const post of posts||[]){let sent=true;for(const subscriber of subscribers||[]){const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${process.env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:process.env.NOTIFICATION_FROM,to:[subscriber.email],subject:`新日志｜${post.title}`,html:emailHtml(post)})});if(!response.ok){sent=false;results.push({post:post.slug,email:subscriber.email,error:await response.text()})}}if(sent){await db.from('posts').update({notification_sent_at:new Date().toISOString()}).eq('id',post.id);results.push({post:post.slug,sent:(subscribers||[]).length})}}return Response.json({processed:posts?.length||0,results})}
export async function GET(request){if(request.headers.get('authorization')!==`Bearer ${process.env.CRON_SECRET}`)return Response.json({error:'unauthorized'},{status:401});return deliver()}
export async function POST(){const session=await createSessionClient();const {data:{user}}=await session.auth.getUser();if(!user)return Response.json({error:'unauthorized'},{status:401});return deliver()}
